### ISSUE TITLE
Satellite transition peak intensity for I > 0.5

### ISSUE THREAD

**Issue by RyanJMcCarty** [smeerten/ssnake#83]
When simulating quadrupolar peak shapes the intensity of the individual spinning side bands are determined by the number of satellites calculated. If numssb = 100 (more sidebands than needed), the generated peak intensities are correct. If numssb = 2, the fid is generated such that the satellite transitions are as intense as the central transition (the full intensity of the satellite transition is given to the side-bands, resulting in two very large SSB). I am not sure how best to fix this, since determining the correct intensity requires knowing how many side bands to calculate. Traced the code back to simFunctions.py to see if I could fix it, but I got lost without comments or notes to explain a few things.

I ran into this error when using 32 SSB, and it took me a while to figure out why ssNAKE had different sidebands than STARS and DMFit. I don't know how they handle this issue, but possibly by just calculating the full static peak shape width?

**Comment by smeerten** [comment]
Incorrect intensities are expected if numssb is smaller than the number of significant sidebands. This is because ssNake uses the carousel averaging [Edén, Concepts in Magnetic Resonance Part A, Vol. 18A(1) 24–55 (2003)]. This algorithm is very efficient, however, it causes aliasing of intensity when numssb is lower than the actual number of sidebands. I think this issue should be be made more clear in the reference manual. Also it should mention that for efficiency of the simulation numssb should be a power of 2.
