### ISSUE TITLE
Referencing issues with frequency/intensity "XR" datasets. Possible import function for DMFit-like data?

### ISSUE THREAD

**Issue by hbrmn** [smeerten/ssnake#88]
Hi,

I am experiencing issues with datasets in the "DMFit" format, i.e. frequency data in XR format. After stripping the two first lines stating the experiments title and the spectrometer frequency 
```
ti: some title
freq##121.500
33407.44708	47.156
33405.1386	46.3856
33402.83013	46.1304
33400.52165	46.4032
.
.
.
```
the dataset can then be correctly loaded in ssNake: (unfortunately running on windows the abcissa caption is always cut off)
![dataset](https://user-images.githubusercontent.com/67208403/85422076-b2d6cc80-b564-11ea-80c7-c3dbb9a51824.PNG)

However, upon updating the spectrometer frequency (the exact value doesn't matter) the data gets shifted on the frequency axis by some fixed amount that depends on the dataset's order of the frequency axis.

A dataset with frequencies ranging from positive to negative values yields:
![p_to_n_after](https://user-images.githubusercontent.com/67208403/85422445-24167f80-b565-11ea-897f-1a3ee71aee6f.PNG)

A dataset with frequencies ranging from negative to positive values yields:
![n_to_p_after](https://user-images.githubusercontent.com/67208403/85422430-2082f880-b565-11ea-9090-98a629b1b030.PNG)

This occurs on both, master and develop, branches to me. Other datasets in "RI" format, generated by SIMPSON, work fine.

Considering the usefulness to store NMR data together with the spectrometer frequency, I believe an option to easily import DMFit-like datasets, where the spectrometer frequency then gets automatically filled-in, would be quite appreciable.

Thanks and all the best
Henrik B.

**Comment by smeerten** [comment]
The reason this happens is because ssNake cannot assume regular spacing between datapoints when loading ASCII data. So any x-axis provided in the file is treated like a "custom x-axis". This will be replaced by an x-axis calculated based on frequency, spectral width, and reference whenever an operation requires equally spaced data, such as changing the freq or sw, or performing a Fourier transform.

Being able to load DMFit data, for which we can safely assume regular spacing, together with the spectrometer frequency is a good idea. And I've included this in ssNake.

**Comment by wfranssen** [comment]
Dear Henrik,

I cannot reproduce the problems you have with the axis labels. I think this is due to the large font size in your image. How did you get this font size so large? Did you change any setting for this? It should be more or less the size of the other text in the interface by default.

Ideally, the plotting library should make sure everything fits in the screen, regardless of font sizes. But there are some limitations to that unfortunately...

Regards,

Wouter

**Comment by hbrmn** [comment]
@smeerten Thank you for the explanation and adressing my suggestion. The DMFit import works nicely.
@wfranssen I got the label issues without making any additional settings when I ran ssNake from spyder out of convenience. However, running ssNake directly from console now displays all labels in regular size, so all is well.

Thanks
Henrik
